### ISSUE TITLE
Como mod maker error (Resolved)

### ISSUE THREAD

**Issue by lzrd34** [bijx/ARMA-3-Camo-Mod-Maker#15]
![image](https://github.com/bijx/ARMA-3-Camo-Mod-Maker/assets/167396018/95cdef09-ce5c-48ce-9d81-cf8be24f48d5)
When attempting to create mod I keep getting this error message, I'm not sure why though. As I thought followed every single step in the tutorial when setting up. Is it possible I could get some help for this?

Thanks! :)

UPDATE: RESOLVED
Had to open Arma 3 tools first and was able to create the mod no issue :)

**Comment by bijx** [comment]
Hey @lzrd34, I was just writing out some comments to see if I could help you figure it out but I guess you got it! Could you put a few more details in the chat here just in case others are having a similar issue, mainly following this format:

**Steps to Reproduce Issue:**

**Steps to Resolve Problem**

Thanks for opening the issue, happy mod making!
